Implemented Rolit game
awslabs/eb-java-scorekeep pull request #12
Opened 2018-11-06 13:18 UTC by AlmazSamatov

2018-11-06 17:56 UTC, mwunderl commented
Thanks for your contribution! I'll take a look.

2018-11-06 19:09 UTC, AlmazSamatov commented
Ok. Good.

2018-11-29 23:01 UTC, mwunderl requested changes
Thanks for your patience. Let me know if you have questions.

2018-11-29 23:01 UTC, mwunderl commented on public/app/scorekeep.js
> +
revert these changes

2018-11-29 23:01 UTC, mwunderl commented on src/main/java/scorekeep/Pair.java
> +/*
remove copyright

2018-11-29 23:01 UTC, mwunderl commented on src/main/java/scorekeep/SimpleCORSFilter.java
> +    config.addAllowedOrigin("http://Scorekeep-env.sdap22vsfv.us-east-1.elasticbeanstalk.com/api/");
revert this change

2018-11-29 23:01 UTC, mwunderl commented on src/main/java/scorekeep/Sns.java
>    }
revert these changes

2018-11-29 23:01 UTC, mwunderl commented on src/main/java/scorekeep/WebConfig.java
>  }
revert these changes

2022-04-11 22:44 UTC, closed without merging